project:
  type: book

book:
  title: "Statistical Analytics with jamovi"
  author: "Dr. Kam Tin Seong"
  date: "20/07/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Interactive Data Exploration and Analysis (IDEA)"
      chapters: 
      - chap02.qmd
    - part: "Frequentist Statistical Analysis"
      chapters:
      - chap03.qmd
      - chap04.qmd
      - chap05.qmd
      - chap06.qmd
      - chap07.qmd
      - chap08.qmd
      - chap09.qmd
    - part: "Bayesian Data Analysis" 
      chapters:
      - chap10.qmd
      - chap11.qmd
      - chap12.qmd
      - chap13.qmd
      - chap14.qmd
      - chap15.qmd
      - chap16.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

